import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/shared/status-badge";

export function ProvenancePanel() {
  return (
    <Card className="overflow-hidden">
      <CardHeader>
        <p className="eyebrow">Trust boundaries</p>
        <CardTitle>Evidence and inference stay separated in the UI.</CardTitle>
      </CardHeader>
      <CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="space-y-2 rounded-[24px] border border-white/10 bg-white/[0.03] p-4">
          <StatusBadge status="draft" label="AI Hypothesis" />
          <p className="text-sm text-[var(--muted-foreground)]">
            Generated by the system and always shown as a proposal, never as an executed fact.
          </p>
        </div>
        <div className="space-y-2 rounded-[24px] border border-white/10 bg-white/[0.03] p-4">
          <StatusBadge status="approved" label="Human Approval" />
          <p className="text-sm text-[var(--muted-foreground)]">
            Human approval is visible with reviewer identity, role, rationale, and timestamp.
          </p>
        </div>
        <div className="space-y-2 rounded-[24px] border border-white/10 bg-white/[0.03] p-4">
          <StatusBadge status="executed" label="Executed Action" />
          <p className="text-sm text-[var(--muted-foreground)]">
            Execution status is rendered separately from planning so the operator can audit the path.
          </p>
        </div>
        <div className="space-y-2 rounded-[24px] border border-white/10 bg-white/[0.03] p-4">
          <StatusBadge status="confirmed" label="Evidence-backed" />
          <p className="text-sm text-[var(--muted-foreground)]">
            Findings, raw evidence, and narrative inference are displayed in separate surfaces.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

